Repository dnd-side-project/dnd-12th-10-backend, pull requests merged in 2025-02, with the labels that each got.

#31 Feature/#29 retrospect
  src/main/java/com/dnd/reevserver/domain/retrospect/controller/RetrospectController.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/request/AddRetrospectRequestDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/request/GetAllGroupRetrospectRequestDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/request/GetRetrospectRequestDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/response/AddRetrospectResponseDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/response/RetrospectResponseDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/exception/RetrospectNotFoundException.java
  src/main/java/com/dnd/reevserver/domain/retrospect/repository/RetrospectRepository.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
Labels: feature

#34 Feature/#30 favorite group
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamController.java
  src/main/java/com/dnd/reevserver/domain/team/dto/request/AddFavoriteGroupRequestDto.java
  src/main/java/com/dnd/reevserver/domain/team/dto/request/GetAllFavoriteGroupRequestDto.java
  src/main/java/com/dnd/reevserver/domain/team/dto/response/AddFavoriteGroupResponseDto.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
  src/main/java/com/dnd/reevserver/domain/userTeam/entity/UserTeam.java
  src/main/java/com/dnd/reevserver/domain/userTeam/exception/UserGroupNotFoundException.java
  src/main/java/com/dnd/reevserver/domain/userTeam/repository/UserTeamRepository.java
Labels: feature

#37 Refactor/#32 변수명 통일
  src/main/java/com/dnd/reevserver/domain/category/entity/TeamCategory.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/response/RetrospectResponseDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/repository/RetrospectRepository.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
  src/main/java/com/dnd/reevserver/domain/team/dto/request/AddTeamRequestDto.java
  src/main/java/com/dnd/reevserver/domain/team/dto/response/AddTeamResponseDto.java
  src/main/java/com/dnd/reevserver/domain/team/dto/response/TeamResponseDto.java
  src/main/java/com/dnd/reevserver/domain/team/entity/Team.java
  src/main/java/com/dnd/reevserver/domain/team/exception/TeamNotFoundException.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
  src/main/java/com/dnd/reevserver/domain/userTeam/entity/UserTeam.java
  src/main/java/com/dnd/reevserver/domain/userTeam/repository/UserTeamRepository.java
Labels: refactor

#42 Feature/#39 retrospect
  src/main/java/com/dnd/reevserver/domain/retrospect/controller/RetrospectController.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/request/DeleteRetrospectRequestDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/request/UpdateRetrospectRequestDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/response/DeleteRetrospectResponseDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/entity/Retrospect.java
  src/main/java/com/dnd/reevserver/domain/retrospect/exception/RetrospectAuthorException.java
  src/main/java/com/dnd/reevserver/domain/retrospect/repository/RetrospectRepository.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
Labels: feature

#44 Feature/#41 join group
  src/main/java/com/dnd/reevserver/domain/member/entity/Member.java
  src/main/java/com/dnd/reevserver/domain/member/service/MemberService.java
  src/main/java/com/dnd/reevserver/domain/retrospect/controller/RetrospectController.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/request/GetRetrospectRequestDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamController.java
  src/main/java/com/dnd/reevserver/domain/team/dto/request/JoinGroupRequestDto.java
  src/main/java/com/dnd/reevserver/domain/team/dto/request/LeaveGroupRequestDto.java
  src/main/java/com/dnd/reevserver/domain/team/dto/response/JoinGroupResponseDto.java
  src/main/java/com/dnd/reevserver/domain/team/dto/response/LeaveGroupResponseDto.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
  src/main/java/com/dnd/reevserver/domain/userTeam/exception/UserGroupExistException.java
Labels: feature

#49 Feature/#48 comment
  src/main/java/com/dnd/reevserver/domain/comment/controller/CommentController.java
  src/main/java/com/dnd/reevserver/domain/comment/dto/request/AddCommentRequestDto.java
  src/main/java/com/dnd/reevserver/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/dnd/reevserver/domain/comment/entity/Comment.java
  src/main/java/com/dnd/reevserver/domain/comment/repository/CommentRepository.java
  src/main/java/com/dnd/reevserver/domain/comment/service/CommentService.java
Labels: feature

#54 refactor:내가 속한 모임 memberController에서 담당하게 변경
  src/main/java/com/dnd/reevserver/domain/member/controller/MemberController.java
  src/main/java/com/dnd/reevserver/domain/member/dto/request/GetAllUserGroupRequestDto.java
  src/main/java/com/dnd/reevserver/domain/member/repository/MemberRepository.java
  src/main/java/com/dnd/reevserver/domain/member/service/MemberService.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamController.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
Labels: refactor

#57 Feature/#56 reply
  src/main/java/com/dnd/reevserver/domain/comment/controller/CommentController.java
  src/main/java/com/dnd/reevserver/domain/comment/dto/request/AddReplyRequestDto.java
  src/main/java/com/dnd/reevserver/domain/comment/dto/response/ReplyResponseDto.java
  src/main/java/com/dnd/reevserver/domain/comment/entity/Comment.java
  src/main/java/com/dnd/reevserver/domain/comment/exception/NotFoundCommentException.java
  src/main/java/com/dnd/reevserver/domain/comment/repository/CommentRepository.java
  src/main/java/com/dnd/reevserver/domain/comment/service/CommentService.java
Labels: feature

#60 feat : 관심있는 키워드 추가
  src/main/java/com/dnd/reevserver/domain/member/dto/request/InsertInfoRequestDto.java
  src/main/java/com/dnd/reevserver/domain/member/entity/FeatureKeyword.java
  src/main/java/com/dnd/reevserver/domain/member/repository/FeatureKeywordRepository.java
  src/main/java/com/dnd/reevserver/domain/member/service/MemberService.java
Labels: feature

#62 Feature/#61 swagger
  src/main/java/com/dnd/reevserver/domain/category/controller/CategoryController.java
  src/main/java/com/dnd/reevserver/domain/category/controller/CategoryControllerDocs.java
  src/main/java/com/dnd/reevserver/domain/comment/controller/CommentController.java
  src/main/java/com/dnd/reevserver/domain/comment/controller/CommentControllerDocs.java
  src/main/java/com/dnd/reevserver/domain/retrospect/controller/RetrospectController.java
  src/main/java/com/dnd/reevserver/domain/retrospect/controller/RetrospectControllerDocs.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamController.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamControllerDocs.java
  src/main/java/com/dnd/reevserver/global/config/swagger/SwaggerConfig.java
Labels: feature

#66 Refactor/#65 time string util
  src/main/java/com/dnd/reevserver/domain/comment/service/CommentService.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
  src/main/java/com/dnd/reevserver/global/util/TimeStringUtil.java
Labels: refactor

#71 Feature/#70 group
  src/main/java/com/dnd/reevserver/domain/team/dto/request/AddTeamRequestDto.java
  src/main/java/com/dnd/reevserver/domain/team/dto/response/TeamResponseDto.java
  src/main/java/com/dnd/reevserver/domain/team/entity/Team.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
Labels: feature

#74 feat:한줄소개 추가
  src/main/java/com/dnd/reevserver/domain/team/dto/request/AddTeamRequestDto.java
  src/main/java/com/dnd/reevserver/domain/team/dto/response/TeamResponseDto.java
  src/main/java/com/dnd/reevserver/domain/team/entity/Team.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
Labels: feature

#76 템플릿 카테고리 추가 및 닉네임 중복
  src/main/java/com/dnd/reevserver/domain/category/entity/TemplateCategory.java
  src/main/java/com/dnd/reevserver/domain/category/repository/TemplateCategoryRepository.java
  src/main/java/com/dnd/reevserver/domain/member/exception/MemberNicknameAlreadyExistedException.java
  src/main/java/com/dnd/reevserver/domain/member/repository/MemberRepository.java
  src/main/java/com/dnd/reevserver/domain/member/service/MemberService.java
  src/main/java/com/dnd/reevserver/domain/template/dto/request/CreateTemplateRequestDto.java
  src/main/java/com/dnd/reevserver/domain/template/dto/request/UpdateTemplateRequestDto.java
  src/main/java/com/dnd/reevserver/domain/template/entity/Template.java
  src/main/java/com/dnd/reevserver/domain/template/exception/UnauthorizedTemplateException.java
  src/main/java/com/dnd/reevserver/domain/template/service/TemplateService.java
Labels: feature

#78 Feature/#77 retro count
  src/main/java/com/dnd/reevserver/domain/retrospect/repository/RetrospectRepository.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
  src/main/java/com/dnd/reevserver/domain/team/dto/response/TeamResponseDto.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
Labels: feature

#79 Feature/#72 popular
  src/main/java/com/dnd/reevserver/domain/member/repository/FeatureKeywordRepository.java
  src/main/java/com/dnd/reevserver/domain/member/service/FeatureKeywordService.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamController.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamControllerDocs.java
  src/main/java/com/dnd/reevserver/domain/team/dto/request/GetRecommendGroupRequestDto.java
  src/main/java/com/dnd/reevserver/domain/team/repository/TeamRepository.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
Labels: feature

#80 feat:인기모임 조회시 최근글도 하나 조회
  src/main/java/com/dnd/reevserver/domain/retrospect/repository/RetrospectRepository.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamController.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamControllerDocs.java
  src/main/java/com/dnd/reevserver/domain/team/dto/response/GetPopularGroupResponseDto.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
Labels: feature

#82 Feature/#81 personal retro
  src/main/java/com/dnd/reevserver/domain/retrospect/controller/RetrospectController.java
  src/main/java/com/dnd/reevserver/domain/retrospect/controller/RetrospectControllerDocs.java
  src/main/java/com/dnd/reevserver/domain/retrospect/repository/RetrospectRepository.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
Labels: feature

#85 Fix/#84 group
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
Labels: fix

#87 Feat/#86 요구사항 반영
  src/main/java/com/dnd/reevserver/domain/member/entity/role/Role.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamController.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamControllerDocs.java
  src/main/java/com/dnd/reevserver/domain/team/dto/response/GroupDetailResponseDto.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
  src/main/java/com/dnd/reevserver/global/util/TimeStringUtil.java
Labels: feature

#91 Feature/#90 comment
  src/main/java/com/dnd/reevserver/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/dnd/reevserver/domain/comment/dto/response/ReplyResponseDto.java
  src/main/java/com/dnd/reevserver/domain/comment/entity/Comment.java
  src/main/java/com/dnd/reevserver/domain/comment/service/CommentService.java
Labels: feature
