Repository dnd-side-project/dnd-12th-10-backend, pull requests merged in 2025-03, with the labels that each got.

#93 Feat/#88 stat
  build.gradle
  src/main/java/com/dnd/reevserver/domain/category/entity/MemoCategory.java
  src/main/java/com/dnd/reevserver/domain/category/repository/MemoCategoryRepository.java
  src/main/java/com/dnd/reevserver/domain/member/controller/AuthController.java
  src/main/java/com/dnd/reevserver/domain/member/controller/MemberController.java
  src/main/java/com/dnd/reevserver/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/dnd/reevserver/domain/member/dto/response/ReissueResponseDto.java
  src/main/java/com/dnd/reevserver/domain/member/service/MemberService.java
  src/main/java/com/dnd/reevserver/domain/memo/controller/MemoController.java
  src/main/java/com/dnd/reevserver/domain/memo/dto/request/CreateMemoRequestDto.java
  src/main/java/com/dnd/reevserver/domain/memo/dto/response/MemoResponseDto.java
  src/main/java/com/dnd/reevserver/domain/memo/entity/Memo.java
  src/main/java/com/dnd/reevserver/domain/memo/service/MemoService.java
  src/main/java/com/dnd/reevserver/domain/statistics/service/LambdaService.java
  src/main/java/com/dnd/reevserver/domain/template/dto/response/TemplateResponseDto.java
  src/main/java/com/dnd/reevserver/domain/template/entity/Template.java
  src/main/java/com/dnd/reevserver/domain/template/repository/TemplateRepository.java
  src/main/java/com/dnd/reevserver/domain/template/service/TemplateService.java
Labels: feature

#94 Refactor/#92 jpa
  src/main/java/com/dnd/reevserver/domain/category/repository/CategoryRepository.java
  src/main/java/com/dnd/reevserver/domain/category/repository/MemoCategoryRepository.java
  src/main/java/com/dnd/reevserver/domain/category/repository/TemplateCategoryRepository.java
  src/main/java/com/dnd/reevserver/domain/category/repository/batch/MemoCategoryBatchRepository.java
  src/main/java/com/dnd/reevserver/domain/category/repository/batch/TemplateCategoryBatchRepository.java
  src/main/java/com/dnd/reevserver/domain/memo/repository/MemoRepository.java
  src/main/java/com/dnd/reevserver/domain/memo/service/MemoService.java
  src/main/java/com/dnd/reevserver/domain/template/repository/TemplateRepository.java
  src/main/java/com/dnd/reevserver/domain/template/service/TemplateService.java
Labels: fix, refactor

#97 Refactor/#95 comment jpa
  build.gradle
  src/main/java/com/dnd/reevserver/domain/alert/service/AlertService.java
  src/main/java/com/dnd/reevserver/domain/comment/controller/CommentController.java
  src/main/java/com/dnd/reevserver/domain/comment/controller/CommentControllerDocs.java
  src/main/java/com/dnd/reevserver/domain/comment/repository/CommentRepository.java
  src/main/java/com/dnd/reevserver/domain/comment/service/CommentService.java
  src/main/java/com/dnd/reevserver/domain/member/entity/Member.java
  src/main/java/com/dnd/reevserver/domain/member/repository/FeatureKeywordBatchRepository.java
  src/main/java/com/dnd/reevserver/domain/member/repository/MemberRepository.java
  src/main/java/com/dnd/reevserver/domain/member/service/MemberService.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
  src/main/java/com/dnd/reevserver/domain/team/repository/TeamRepository.java
  src/main/java/com/dnd/reevserver/domain/userTeam/service/UserTeamService.java
  src/main/resources/logback.xml
Labels: feature, refactor

#100 Refactor/#99 fetch
  src/main/java/com/dnd/reevserver/domain/member/service/MemberService.java
  src/main/java/com/dnd/reevserver/domain/retrospect/controller/RetrospectController.java
  src/main/java/com/dnd/reevserver/domain/retrospect/repository/RetrospectRepository.java
  src/main/java/com/dnd/reevserver/domain/team/repository/TeamRepository.java
Labels: refactor

#103 Feature/#68 querydsl
  build.gradle
  src/main/java/com/dnd/reevserver/domain/querydslTest/QuerydslTestService.java
  src/main/java/com/dnd/reevserver/domain/querydslTest/queryDslTestController.java
Labels: feature

#106 fix : 좋아요 API의 동시성 문제를 Redis로 해결
  src/main/java/com/dnd/reevserver/domain/like/controller/LikeController.java
  src/main/java/com/dnd/reevserver/domain/like/repository/LikeRepository.java
  src/main/java/com/dnd/reevserver/domain/like/service/LikeService.java
  src/main/java/com/dnd/reevserver/domain/retrospect/entity/Retrospect.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
  src/main/java/com/dnd/reevserver/global/config/redis/RedisConfig.java
Labels: fix, refactor

#111 Feature/#110 group ud
  src/main/java/com/dnd/reevserver/domain/category/repository/TeamCategoryRepository.java
  src/main/java/com/dnd/reevserver/domain/category/repository/batch/TeamCategoryBatchRepository.java
  src/main/java/com/dnd/reevserver/domain/category/service/TeamCategoryService.java
  src/main/java/com/dnd/reevserver/domain/retrospect/controller/RetrospectController.java
  src/main/java/com/dnd/reevserver/domain/retrospect/repository/RetrospectRepository.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamController.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamControllerDocs.java
  src/main/java/com/dnd/reevserver/domain/team/dto/request/UpdateGroupRequestDto.java
  src/main/java/com/dnd/reevserver/domain/team/entity/Team.java
  src/main/java/com/dnd/reevserver/domain/team/exception/NotOwnerUserException.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
Labels: feature

#113 Feature/#109 bookmark
  src/main/java/com/dnd/reevserver/domain/comment/repository/CommentRepository.java
  src/main/java/com/dnd/reevserver/domain/retrospect/controller/RetrospectController.java
  src/main/java/com/dnd/reevserver/domain/retrospect/controller/RetrospectControllerDocs.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/request/BookmarkRequestDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/response/RetrospectResponseDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/response/RetrospectSingleResponseDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/entity/Bookmark.java
  src/main/java/com/dnd/reevserver/domain/retrospect/entity/Retrospect.java
  src/main/java/com/dnd/reevserver/domain/retrospect/exception/BookmarkAlreadyExistedException.java
  src/main/java/com/dnd/reevserver/domain/retrospect/exception/BookmarkMemberWrongException.java
  src/main/java/com/dnd/reevserver/domain/retrospect/exception/BookmarkNotFoundException.java
  src/main/java/com/dnd/reevserver/domain/retrospect/repository/BookmarkRepository.java
  src/main/java/com/dnd/reevserver/domain/retrospect/repository/RetrospectRepository.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
Labels: feature, refactor

#114 Feature/#112 comment ud
  src/main/java/com/dnd/reevserver/domain/comment/controller/CommentController.java
  src/main/java/com/dnd/reevserver/domain/comment/controller/CommentControllerDocs.java
  src/main/java/com/dnd/reevserver/domain/comment/dto/request/UpdateCommentRequestDto.java
  src/main/java/com/dnd/reevserver/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/dnd/reevserver/domain/comment/dto/response/DeleteCommentResponseDto.java
  src/main/java/com/dnd/reevserver/domain/comment/dto/response/ReplyResponseDto.java
  src/main/java/com/dnd/reevserver/domain/comment/entity/Comment.java
  src/main/java/com/dnd/reevserver/domain/comment/exception/NotCommentOwnerException.java
  src/main/java/com/dnd/reevserver/domain/comment/service/CommentService.java
  src/main/java/com/dnd/reevserver/domain/querydslTest/QuerydslTestService.java
  src/main/java/com/dnd/reevserver/domain/querydslTest/queryDslTestController.java
Labels: feature
