Repository dnd-side-project/dnd-12th-10-backend, pull requests merged in 2025-04, with the labels that each got.

#124 Refactor/#122 removing redis
  build.gradle
  src/main/java/com/dnd/reevserver/domain/like/controller/LikeController.java
  src/main/java/com/dnd/reevserver/domain/like/repository/LikeRepository.java
  src/main/java/com/dnd/reevserver/domain/like/service/LikeService.java
  src/main/java/com/dnd/reevserver/domain/like/service/SqsProducer.java
  src/main/java/com/dnd/reevserver/domain/member/repository/RefreshTokenRepository.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
  src/main/java/com/dnd/reevserver/global/config/dynamodb/DynamodbConfig.java
  src/main/java/com/dnd/reevserver/global/config/redis/RedisConfig.java
  src/main/java/com/dnd/reevserver/global/jwt/filter/JwtAuthenticationFilter.java
Labels: feature, fix, refactor

#127 refactor : actions가 EC2에 ssh로 접근하는 것 대신 CodeDeploy를 트리거시키게 함
  .github/workflows/deploy.yml
Labels: refactor

#129 Refactor/#128 alram stat
  build.gradle
  src/main/java/com/dnd/reevserver/domain/alert/controller/AlertController.java
  src/main/java/com/dnd/reevserver/domain/alert/dto/response/AlertListResponseDto.java
  src/main/java/com/dnd/reevserver/domain/alert/dto/response/AlertMessageResponseDto.java
  src/main/java/com/dnd/reevserver/domain/alert/repository/AlertRepository.java
  src/main/java/com/dnd/reevserver/domain/alert/service/AlertMessageListener.java
  src/main/java/com/dnd/reevserver/domain/alert/service/AlertService.java
  src/main/java/com/dnd/reevserver/domain/alert/service/AlertSqsProducer.java
  src/main/java/com/dnd/reevserver/domain/like/controller/LikeController.java
  src/main/java/com/dnd/reevserver/domain/like/service/LikeService.java
  src/main/java/com/dnd/reevserver/domain/like/service/LikeSqsProducer.java
  src/main/java/com/dnd/reevserver/domain/member/controller/AuthController.java
  src/main/java/com/dnd/reevserver/domain/member/controller/MemberController.java
  src/main/java/com/dnd/reevserver/domain/memo/controller/MemoController.java
  src/main/java/com/dnd/reevserver/domain/retrospect/controller/RetrospectController.java
  src/main/java/com/dnd/reevserver/domain/retrospect/repository/RetrospectRepository.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
  src/main/java/com/dnd/reevserver/domain/statistics/controller/StatisticsController.java
  src/main/java/com/dnd/reevserver/domain/statistics/dto/response/GetRetrospectStatsResponseDto.java
  src/main/java/com/dnd/reevserver/domain/statistics/dto/response/MonthlyActivityStatsResponseDto.java
  src/main/java/com/dnd/reevserver/domain/statistics/dto/response/MonthlyComparisonStatsResponseDto.java
  src/main/java/com/dnd/reevserver/domain/statistics/repository/StatisticsRedisRepository.java
  src/main/java/com/dnd/reevserver/domain/statistics/repository/StatisticsRepository.java
  src/main/java/com/dnd/reevserver/domain/statistics/service/LambdaService.java
  src/main/java/com/dnd/reevserver/domain/statistics/service/StatisticsService.java
  src/main/java/com/dnd/reevserver/domain/template/controller/TemplateController.java
  src/main/java/com/dnd/reevserver/global/config/redis/RedisConfig.java
  src/main/java/com/dnd/reevserver/global/config/sqs/SQSConfig.java
  src/main/java/com/dnd/reevserver/global/config/swagger/SwaggerConfig.java
Labels: feature, fix, refactor

#131 Feature/#115 그룹탐색
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamController.java
  src/main/java/com/dnd/reevserver/domain/team/controller/TeamControllerDocs.java
  src/main/java/com/dnd/reevserver/domain/team/dto/request/GroupSearchCondition.java
  src/main/java/com/dnd/reevserver/domain/team/repository/TeamRepository.java
  src/main/java/com/dnd/reevserver/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/dnd/reevserver/domain/team/repository/TeamRepositoryCustomImpl.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
  src/main/java/com/dnd/reevserver/global/config/querydslConfig/QuerydslConfig.java
  src/main/java/com/dnd/reevserver/global/exception/GeneralException.java
Labels: feature

#134 Feature/#133 retrosepct category
  src/main/java/com/dnd/reevserver/domain/category/entity/RetrospectCategory.java
  src/main/java/com/dnd/reevserver/domain/category/repository/RetrospectCategoryRepository.java
  src/main/java/com/dnd/reevserver/domain/category/repository/batch/RetrospectCategoryBatchRepository.java
  src/main/java/com/dnd/reevserver/domain/comment/service/CommentService.java
  src/main/java/com/dnd/reevserver/domain/memo/dto/response/MemoResponseDto.java
  src/main/java/com/dnd/reevserver/domain/memo/entity/Memo.java
  src/main/java/com/dnd/reevserver/domain/memo/service/MemoService.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/request/AddRetrospectRequestDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/request/UpdateRetrospectRequestDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/response/RetrospectResponseDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/dto/response/RetrospectSingleResponseDto.java
  src/main/java/com/dnd/reevserver/domain/retrospect/repository/RetrospectRepository.java
  src/main/java/com/dnd/reevserver/domain/retrospect/service/RetrospectService.java
  src/main/java/com/dnd/reevserver/domain/statistics/repository/StatisticsRedisRepository.java
  src/main/java/com/dnd/reevserver/domain/statistics/service/StatisticsService.java
  src/main/java/com/dnd/reevserver/domain/team/service/TeamService.java
  src/main/java/com/dnd/reevserver/domain/template/dto/response/TemplateResponseDto.java
Labels: feature
